cmake_minimum_required(VERSION 3.22)
project(garden_simulation LANGUAGES CXX)
find_package(gz-sim8 REQUIRED)
add_executable(garden-sim-server server.cc)
target_link_libraries(garden-sim-server PRIVATE gz-sim8::gz-sim8)
target_compile_features(garden-sim-server PRIVATE cxx_std_17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(trajectory_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(rosgraph_msgs REQUIRED)
find_package(tf2_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(nav_msgs REQUIRED)
add_library(garden-ros-adapter SHARED ros_adapter.cc)
target_link_libraries(garden-ros-adapter gz-sim8::gz-sim8)
ament_target_dependencies(garden-ros-adapter rclcpp geometry_msgs trajectory_msgs sensor_msgs rosgraph_msgs tf2_msgs std_msgs nav_msgs)
target_compile_features(garden-ros-adapter PRIVATE cxx_std_17)
